apiVersion: apps/v1

kind: Deployment

metadata:
  name: mysql
  labels:
    app: mysqlserver
  name: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secret55"
        ports:
         - containerPort: 3306
           protocol: TCP