apiVersion: v1

kind: Pod

metadata:
  labels:
    app: mysqlserver
  name: mysql

spec:
  containers:
    - name: mysql
      image: 
      ports:
       - containerPort: 3306
         protocol: TCP

      env:
       - name: MYSQL_ROOT_PASSWORD
         value: "secret55"